// GENERATED by tools/gen_mcm_table.py from Frostfall's own MCM script, Frostfall.esp and English strings. Do not edit by hand.
// Frostfall is by Chesko; its scripts and plugin are MIT licensed (the meshes and textures are not part of this).
#pragma once

#include <iterator>

// The local FormID of a record in Frostfall.esp: the first value in the regular build, the second (compacted) one in the ESL build.
#ifdef FROSTFALL_ESL
#define FF_ID(regular, esl) esl
#else
#define FF_ID(regular, esl) regular
#endif

namespace mcm
{
	enum class Kind { Header, Column, Toggle, Slider, Menu, Key };

	// One row of a page. formId is the local FormID of the setting's global (0 for headers and column breaks).
	// Toggles hold 1 (off) or 2 (on). A menu stores its list position plus menuBase. Slider: min, max, step; isFloat = saved to the profile as a
	// float. Key: min holds the hotkey slot. gate: the row is greyed out unless this global is 2. special: 1 = shown ticked and greyed while
	// "no waiting" is on, 2 = hidden when the optional SkyUI interface package shows these notifications itself.
	struct Entry
	{
		Kind        kind;
		const char* label;
		unsigned    formId;
		const char* profileKey;
		float       min, max, step;
		int         isFloat;
		const char* format;
		const char* const* options;
		int         optionCount;
		int         menuBase;
		unsigned    gate;
		int         special;
		const char* tip;
	};

	struct Page
	{
		const char*  title;
		const Entry* entries;
		int          count;
	};

	inline constexpr unsigned kMcmQuest = FF_ID(0x06DCF8, 0x000A97);
	inline constexpr unsigned kFrostSettingAutoSaveLoad = FF_ID(0x06DCF9, 0x000A98);
	inline constexpr unsigned kFrostSettingCurrentProfile = FF_ID(0x06DCFA, 0x000A99);
	inline constexpr unsigned kEndurancePerkPointsTotal = FF_ID(0x06811C, 0x000A50);
	inline constexpr unsigned kFrostHelpDoneExposure = FF_ID(0x04000B, 0x000894);
	inline constexpr unsigned kFrostHelpDoneWet = FF_ID(0x04000C, 0x000895);
	inline constexpr unsigned kFrostHelpDoneCold = FF_ID(0x04000E, 0x000896);
	inline constexpr unsigned kFrostDatastoreInitialized = FF_ID(0x065B31, 0x000A17);

	inline constexpr const char* kList_Gameplay_MaxExposureMode_OID[] = { "Nothing", "Rescue", "Death" };
	inline constexpr const char* kList_Gameplay_VampirismMode_OID[] = { "Mortal", "Supernatural", "Immortal" };
	inline constexpr const char* kList_Interface_Animation_OID[] = { "Off", "Auto", "Prompt" };
	inline constexpr const char* kList_Interface_WeathersenseDisplayMode_OID[] = { "Text", "Meters", "Text, Meters" };

	inline constexpr Entry kPage0[] = {
		{ Kind::Header, "Player", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "" },
		{ Kind::Slider, "Exposure Rate", FF_ID(0x011BE4, 0x000838), "exposure_rate", 0.0f, 3.0f, 0.1f, 1, "%.1fx", nullptr, 0, 0, 0, 0, "Adjust the overall rate of exposure. Ranges from 0.0x to 3.0x.\nDefault: 1.0x" },
		{ Kind::Menu, "At Max Exposure:", FF_ID(0x068115, 0x000A49), "max_exposure_mode", 0, 0, 0, 0, "", kList_Gameplay_MaxExposureMode_OID, 3, 1, 0, 0, "Nothing: Nothing happens at maximum exposure.\nRescue: Pass out and awaken somewhere else. The most story-driven option.\nDeath: You and your followers perish." },
		{ Kind::Toggle, "Frigid Water Is Dangerous", FF_ID(0x00E5B7, 0x000837), "frigid_water_is_lethal", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "If enabled, being in frigid water can incapacitate you (if Max Exposure: Rescue enabled) or kill you. If disabled, cold water still saps your stamina.\nDefault: On" },
		{ Kind::Toggle, "Pause Exposure During Dialogue", FF_ID(0x03EA6E, 0x000891), "exposure_pause_dialogue", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "Pause changes to exposure when talking to other NPCs.\nDefault: On" },
		{ Kind::Toggle, "Pause Exposure During Combat", FF_ID(0x068117, 0x000A4B), "exposure_pause_combat", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "Pause changes to exposure during combat (except when hit by spells).\nDefault: On" },
		{ Kind::Toggle, "High Exposure Slows You", FF_ID(0x0430F4, 0x00089D), "movement_penalty", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "If enabled, you will begin to move slowly when 'Freezing', and very slowly when 'Freezing to Death'.\nDefault: On" },
		{ Kind::Menu, "Vampire Behavior:", FF_ID(0x06DD0A, 0x000AA8), "vampire_mode", 0, 0, 0, 0, "", kList_Gameplay_VampirismMode_OID, 3, 0, 0, 0, "Mortal: Exposure affects you normally, even as a vampire.\nSupernatural: You are immune to Frostbite and gain +100 Warmth. Penalties still apply.\nImmortal: You are immune to Frostbite and cannot succumb to exposure. Penalties still apply." },
		{ Kind::Header, "Fast Travel & Waiting", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "" },
		{ Kind::Toggle, "Disable Fast Travel", FF_ID(0x01AE47, 0x000847), "no_fast_travel", 0, 0, 0, 0, "", nullptr, 0, 0, FF_ID(0x06DD0B, 0x000AA9), 1, "Whether or not to disable Fast Travel.\nIt may take up to 5 seconds for this setting to take effect after you change it.\nDefault: Off" },
		{ Kind::Toggle, "Disable Waiting while Outdoors", FF_ID(0x06DD0B, 0x000AA9), "no_waiting", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "Whether or not to disable waiting while outdoors. If disabled, you will still be able to wait while inside. It may take up to 5 seconds for this setting to take effect after you change it.\nWARNING: Disabling waiting outdoors will also disable Fast Travel.\nDefault: Off" },
		{ Kind::Header, "Hotkeys", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "" },
		{ Kind::Key, "Weathersense", FF_ID(0x053011, 0x0008EF), "hotkey_weathersense", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "Click to set a key to quickly use the Weathersense ability.\nThis will remove the Weathersense power from your spell list. Default the hotkey to acquire the power again." },
	};
	inline constexpr Entry kPage1[] = {
		{ Kind::Header, "Effects", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "" },
		{ Kind::Toggle, "Player Frost Shader", FF_ID(0x068120, 0x000A54), "frost_shader_on", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "Toggles the frost effect seen on the player at high levels of exposure.\nGenerally compatible with other mods that add frost effects for the player (e.g. Get Snowy, Wet and Cold).\nDefault: On" },
		{ Kind::Toggle, "Player Wetness Shader", FF_ID(0x064AF4, 0x000A06), "wet_shader_on", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "Toggles the dripping water effect seen on the player when wet.\nIf you use another mod that shows player wet effects, disable this option for the best visual results.\nDefault: On" },
		{ Kind::Toggle, "Sound Effects", FF_ID(0x048CEC, 0x0008BF), "sound_effects", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "If enabled, you will play a shivering sound effect when you begin 'Freezing' or 'Freezing to Death'.\nDefault: On" },
		{ Kind::Toggle, "Full Screen Effects", FF_ID(0x068116, 0x000A4A), "full_screen_effects", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "Toggles the full screen effects seen at high levels of exposure.\nDefault: On" },
		{ Kind::Toggle, "Force Feedback", FF_ID(0x048CED, 0x0008C0), "force_feedback", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "Controller Users: You will feel a shiver effect when you begin 'Freezing' or 'Freezing to Death'. You will also feel a heartbeat pulse when swimming in frigid water.\nDefault: On" },
		{ Kind::Menu, "Player Hand Warming Animations", FF_ID(0x049268, 0x0008C1), "animation", 0, 0, 0, 0, "", kList_Interface_Animation_OID, 3, 1, 0, 0, "Auto: Warm your hands when facing nearby heat sources in 3rd Person View. Prompt: Warm your hands by pressing Use when prompted when facing nearby heatsources in 1st or 3rd Person View. Off: Never warm your hands.\nThe animation is cosmetic and has no effect on gameplay. Must be standing still with weapons sheathed.\nDefault: Auto" },
		{ Kind::Toggle, "Follower Hand Warming Animations", FF_ID(0x06DD0C, 0x000AAA), "follower_animation", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "If enabled, followers (up to 3) will gather around heat sources and warm their hands when the player does. Requires Player Hand Warming Animations be set to Auto or Prompt.\nDefault: On" },
		{ Kind::Header, "Notifications", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "" },
		{ Kind::Toggle, "Condition Changes", FF_ID(0x03EA72, 0x000893), "condition_messages", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "If enabled, you will receive periodic notifications about changes to your status (exposure and wetness).\nWARNING: This is the primary way Frostfall notifies you of worsening player conditions. Disable at your own risk!\nDefault: On" },
		{ Kind::Toggle, "Weather Transitions", FF_ID(0x066094, 0x000A18), "weather_messages", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "If enabled, you will receive descriptive notifications of changing weather conditions shortly before they occur.\nDefault: On" },
		{ Kind::Menu, "Weathersense Display", FF_ID(0x05E39C, 0x00098B), "weathersense_display_mode", 0, 0, 0, 0, "", kList_Interface_WeathersenseDisplayMode_OID, 3, 0, 0, 0, "Set if a message, meters, or both, should be displayed when using Weathersense." },
		{ Kind::Toggle, "Attribute Descriptions in Weathersense", FF_ID(0x03EA71, 0x000892), "display_attributes_in_weathersense", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "If enabled, Weathersense will show descriptions of your exposure and wetness along with the temperature description.\nDefault: Off" },
		{ Kind::Toggle, "Attribute Values in Weathersense", FF_ID(0x081656, 0x000B30), "display_attribute_values_in_weathersense", 0, 0, 0, 0, "", nullptr, 0, 0, FF_ID(0x03EA71, 0x000892), 0, "If enabled, Weathersense will display your exact exposure and wetness percentages.\nDefault: Off" },
		{ Kind::Toggle, "Warmth / Coverage On Equip", FF_ID(0x06AC6E, 0x000A8C), "notification_equipmentvalues", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 2, "If enabled, you will receive a notification describing the Warmth and Coverage provided by gear that you equip.\nDefault: On" },
		{ Kind::Toggle, "Warmth / Coverage Totals", FF_ID(0x06F2AD, 0x000AB8), "notification_equipmentsummary", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 2, "If enabled, you will receive a notification describing your total Warmth and Coverage when you change equipment.\nDefault: On" },
	};
	inline constexpr Entry kPage2[] = {
		{ Kind::Header, "Tutorials", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "" },
		{ Kind::Toggle, "Show Contextual Tutorials", FF_ID(0x04000F, 0x000897), "display_tutorials", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "" },
	};

	inline constexpr Page kPages[] = {
		{ "Gameplay", kPage0, static_cast<int>(std::size(kPage0)) },
		{ "Interface", kPage1, static_cast<int>(std::size(kPage1)) },
		{ "Advanced", kPage2, static_cast<int>(std::size(kPage2)) },
	};
}
